ar: 'العربية'
cs: 'čeština'
de: 'Deutsch'
en_US: 'English'
es: 'Español'
fr: 'Français'
hu: 'Magyar'
it: 'Italiano'
ja: '日本語'
ko: 'Korean'
nl: 'Nederlands'
pl: 'Polski'
pt_BR: 'Português'
ru: 'Русский'
sv: 'Svenska'
zh_CN: '简体中文'
zh_TW: '繁體中文'
