#======================================================================
#                        HA Web Konsole (Hawk)
# --------------------------------------------------------------------
#            A web-based GUI for managing and monitoring the
#          Pacemaker High-Availability cluster resource manager
#
# Copyright (c) 2009-2015 SUSE LLC, All Rights Reserved.
#
# Author: Tim Serong <tserong@suse.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# Further, this software is distributed without any warranty that it is
# free of the rightful claim of any third person regarding infringement
# or the like.  Any license provided herein, whether implied or
# otherwise, applies only to this software file.  Patent licenses, if
# any, provided herein do not apply to combinations of this program with
# other software, or any other product whatsoever.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston MA 02111-1307, USA.
#
#======================================================================

development:
  secret_key_base: '2c5d384c7ee6cceed52e32a53f307c5cef2f0ac8f04c1d72105baf477cbbf57de047a99ba21295b454a5f29c19f17cbbebf23f18beb58a4c114bb20ec2c38076'

test:
  secret_key_base: 'd83f4c419cbf9a7b1ea115516ab5f4735ec3df709efdbb271c6ac0f503637b1f4c80691063886a6a4314a093b7b50c87768e8ec82276bb62cc3b565cb4e46754'

production:
  secret_key_base: '<%= ENV['SECRET_KEY_BASE'] %>'
